// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: "AIzaSyAV6EcjuTROGb_mv31z1nbE3lPV11LFxuw",
    authDomain: "resume-63067.firebaseapp.com",
    projectId: "resume-63067",
    storageBucket: "resume-63067.firebasestorage.app",
    messagingSenderId: "126462489197",
    appId: "1:126462489197:web:7f655343443eabb4408564",
    measurementId: "G-JK6TPD755E"
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAV6EcjuTROGb_mv31z1nbE3lPV11LFxuw',
    appId: '1:126462489197:android:7f655343443eabb4408564',
    messagingSenderId: '126462489197',
    projectId: 'resume-63067',
    storageBucket: 'resume-63067.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAV6EcjuTROGb_mv31z1nbE3lPV11LFxuw',
    appId: '1:126462489197:ios:7f655343443eabb4408564',
    messagingSenderId: '126462489197',
    projectId: 'resume-63067',
    storageBucket: 'resume-63067.firebasestorage.app',
    iosBundleId: 'net.casim.ccResumeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAV6EcjuTROGb_mv31z1nbE3lPV11LFxuw',
    appId: '1:126462489197:ios:7f655343443eabb4408564',
    messagingSenderId: '126462489197',
    projectId: 'resume-63067',
    storageBucket: 'resume-63067.firebasestorage.app',
    iosBundleId: 'net.casim.ccResumeApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAV6EcjuTROGb_mv31z1nbE3lPV11LFxuw',
    appId: '1:126462489197:web:7f655343443eabb4408564',
    messagingSenderId: '126462489197',
    projectId: 'resume-63067',
    authDomain: 'resume-63067.firebaseapp.com',
    storageBucket: 'resume-63067.firebasestorage.app',
    measurementId: 'G-JK6TPD755E',
  );
}
