name: Deploy to Firebase Hosting on merge
on:
  push:
    branches:
      - master
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.0'
          channel: 'stable'
      - run: flutter pub get
      # Inject the resume_constants file from secret
      - name: Create resume_constants.dart
        run: echo "$RESUME_CONSTANTS" > lib/resume_constants.dart
        env:
          RESUME_CONSTANTS: ${{ secrets.RESUME_CONSTANTS }}
      - name: Create firebase_options.dart
        run: echo "$FIREBASE_OPTIONS" > lib/firebase_options.dart
        env:
          FIREBASE_OPTIONS: ${{ secrets.FIREBASE_OPTIONS }}    
      - run: flutter build web --release
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_RESUME_63067 }}
          channelId: live
          projectId: resume-63067